# version format
version: "{build}"

# Operating system (build VM template)
os: Windows Server 2012 R2

clone_folder: c:\gopath\src\github.com\minio\mc

# environment variables
environment:
  GOPATH: c:\gopath
  GO15VENDOREXPERIMENT: 1

# scripts that run after cloning repository
install:
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - go version
  - go env
  - go get -u github.com/golang/lint/golint
  - go get -u golang.org/x/tools/cmd/vet
  - go get -u github.com/fzipp/gocyclo
  - go get -u github.com/remyoudompheng/go-misc/deadcode
  - go get -u github.com/alecthomas/gometalinter
  - go get -u github.com/client9/misspell

# to run your custom scripts instead of automatic MSBuild
build_script:
  - go tool vet -all ./pkg
  - go tool vet -shadow=true ./pkg
  - gofmt -s -l pkg
  - golint .
  - golint github.com/minio/mc/pkg...
  - gometalinter --disable-all --linter='misspell:misspell ./*.go:PATH:LINE:COL:MESSAGE' --enable=misspell ./...
  - gocyclo -over 40 pkg
  - deadcode
  - go test -race .
  - go test -race github.com/minio/mc/pkg...
  - go run buildscripts/gen-ldflags.go > temp.txt
  - set /p LDFLAGS=<temp.txt
  - go build -ldflags="%LDFLAGS%" -o %GOPATH%\bin\mc.exe
  - mc version

# to disable automatic tests
test: off

# to disable deployment
deploy: off
