name: Go

on:
  pull_request:
    branches:
    - master

jobs:
  build:
    name: Test on Go ${{ matrix.go-version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go-version: [1.16.x]
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Set up Go ${{ matrix.go-version }} on ${{ matrix.os }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Build on ${{ matrix.os }}
        if: matrix.os == 'windows-latest'
        env:
          GO111MODULE: on
        run: |
          go build --ldflags="-s -w" -o %GOPATH%\bin\mc.exe
          go test -v -race --timeout 30m ./...
      - name: Build on ${{ matrix.os }}
        if: matrix.os == 'ubuntu-latest'
        env:
          GO111MODULE: on
        run: |
          make
          diff -au <(gofmt -d *.go) <(printf "")
          diff -au <(gofmt -s -d cmd) <(printf "")
          diff -au <(gofmt -s -d pkg) <(printf "")
          make test-race
          make verify
          make crosscompile
